# Generated by Django 3.2.4 on 2021-06-29 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RequestInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('middle_name', models.CharField(blank=True, max_length=20)),
                ('last_name', models.CharField(blank=True, max_length=20)),
                ('dob', models.DateField(blank=True)),
                ('gender', models.CharField(blank=True, max_length=1)),
                ('nationality', models.CharField(blank=True, max_length=20)),
                ('current_city', models.CharField(blank=True, max_length=30)),
                ('state', models.CharField(blank=True, max_length=20)),
                ('pin_code', models.TextField(blank=True)),
                ('qualification', models.TextField(blank=True)),
                ('salary', models.IntegerField(blank=True)),
                ('pan', models.TextField(blank=True)),
                ('request_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'request_info',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ResponseInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_status', models.TextField(max_length=7)),
                ('reason', models.TextField()),
                ('response_time', models.DateTimeField(auto_now=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='first_app.requestinfo')),
            ],
            options={
                'db_table': 'response_info',
                'managed': True,
            },
        ),
    ]
